export const REQUEST_SUCCESS = 200
export const REQUEST_NOT_FOUND = 404
export const REQUEST_INTERNAL_ERROR = 500
export const REQUEST_ERROR = 400
export const REQUEST_UNRECORNIZED = 401
export const REQUEST_FORBIDDEN = 403
export const SERVICE_CANNOT_USE = 503