export const prizeList = [{
  type: 0,
  subType: 0,
  count: 1,
  title: '特等奖-1',
  img: './img/huawei.png'
}, {
  type: 0,
  subType: 1,
  count: 1,
  title: '特等奖-2',
  img: './img/huawei.png'
}, {
  type: 0,
  subType: 2,
  count: 1,
  title: '特等奖-3',
  img: './img/huawei.png'
}, {
  type: 1,
  subType: 0,
  count: 1,
  title: 'ps5(国行)',
  img: './img/huawei.png'
}, {
  type: 2,
  subType: 0,
  count: 1,
  title: '戴森v10',
  img: './img/huawei.png'
}, {
  type: 2,
  subType: 1,
  count: 1,
  title: '戴森吹风机 hd08',
  img: './img/huawei.png'
}, {
  type: 2,
  subType: 2,
  count: 1,
  title: '坚果p3s投影仪',
  img: './img/huawei.png'
}, {
  type: 2,
  subType: 3,
  count: 1,
  title: 'gopro hero9 black',
  img: './img/huawei.png'
}, {
  type: 3,
  subType: 0,
  count: 1,
  title: 'sony wi-1000xm2 颈挂式入耳无线蓝牙耳机',
  img: './img/huawei.png'
}, {
  type: 3,
  subType: 1,
  count: 2,
  title: 'airpods pro',
  img: './img/huawei.png'
}, {
  type: 4,
  subType: 0,
  count: 4,
  title: 'cherry mx3.0s g80-3870lyaeu-2 机械键盘',
  img: './img/huawei.png'
}, {
  type: 4,
  subType: 1,
  count: 5,
  title: '小熊多功能锅',
  img: './img/huawei.png'
}, {
  type: 4,
  subType: 2,
  count: 2,
  title: 'aca电烤箱',
  img: './img/huawei.png'
}, {
  type: 4,
  subType: 3,
  count: 4,
  title: '惠普 dj2720 打印机',
  img: './img/huawei.png'
}, {
  type: 4,
  subType: 4,
  count: 4,
  title: '摩飞加湿器4l',
  img: './img/huawei.png'
}, {
  type: 4,
  subType: 5,
  count: 2,
  title: 'skg按摩腰带',
  img: './img/huawei.png'
}, {
  type: 4,
  subType: 6,
  count: 2,
  title: 'aca空气炸锅',
  img: './img/huawei.png'
}, {
  type: 4,
  subType: 7,
  count: 2,
  title: '小米小爱音箱pro8',
  img: './img/huawei.png'
}]